apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pypy_build
spec:
  description: >-
    This task builds python package into a pypy library using setuptools.
    Task was specifically developed for Renci Tycho package build. 
  params:
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ['-c', 'echo hello world']