apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-deck
spec:
  workspaces:
    - name: deck
  steps:
    - name: get-deck
      image: jetbrainsinfra/jq
      script: |
        #!/bin/sh
        apk update
        apk fetch curl
        apk add curl
        curl https://www.deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1 | jq .deck_id > $(workspaces.deck.path)/deckID.txt
        echo "Deck info written to $(workspaces.deck.path) in deckID.txt"